### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by izuolan** [zhaoda/blog#9]
不好意思
用issues搭建博客，岂不是其他人也能发表啦？
（看了一下设置，issues无法设置权限，但是wiki系统倒是可以）
此外能不能做到把下面评论加入到文章后面，当做评论呢？

**Comment by zhaoda** [comment]
你好，别人确实也能发表，但是不会显示在你的博客里，因为配置里可以设置只获取你发表的issues，如果别人发别了issues，你可以close掉它们；评论目前没有加入进来，因为有人会使用第三方的评论组件；你可以自行修改代码，把issues里的评论加进来也不复再，多调用一个异步接口然后渲染出来就行。

**Comment by izuolan** [comment]
原来如此，谢谢～～
